### PR TITLE
Port improvements implemented by elbow-jason in his fork

### PR DESCRIPTION
**Pull request by polmuz**
See https://github.com/elbow-jason/elixir-geohash/commit/0db29a76a2403fddb85cacd44374aebdcd2f2e61

### CODE REVIEW

**Comment by polmuz** [comment]
@elbow-jason review please!

**Review by elbow-jason — COMMENTED** [review]
Looks good to me! :)

**Comment by elbow-jason** [comment]
I need to check my notifications more often.

**Comment by polmuz** [comment]
Thanks!

**Pull request merged**
